apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: my-redis
  namespace: testing
spec:
  serviceClassName: azure-rediscache
  planName: basic
  parameters:
    resourceGroup: SOUTHCENTRAL
    cacheName: coreos-redis
    parameters:
      location: southcentralus
      enableNonSslPort: true
      sku:
        name: Basic
        family: C
        capacity: 0
